name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  MYSQL_VERSION: 8
  MYSQL_DB: stefanshoppen
  MYSQL_USER: root
  MYSQL_PASSWORD: hejsan123
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DB: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: mvn -B clean package --file pom.xml
