name: CICD

on:
  push:
    branches: [ main ]

env:
  MYSQL_VERSION: 8
  MYSQL_DB: stefanshoppen
  MYSQL_USER: root
  MYSQL_PASSWORD: hejsan123
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin


jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DB: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: mvn -B clean package --file pom.xml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: stefanshoppenv2
          environment_name: stefanshoppenv2-env
          version_label: ver-${{ github.sha }}
          region: eu-north-1
          deployment_package: target/shop-0.0.1-SNAPSHOT.jar
          wait_for_deployment: 60
