name: CICD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name:
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: stefanshoppenv2
          environment_name: stefanshoppenv2-env
          version_label: ver-${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy_package.zip
